import { StyleSheet } from 'react-native';
import { colors } from '../../theme';
import Typography from '../../theme/fonts';

export const productScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 16,
  },
  headerButton: {
    padding: 8,
    width: 40,
    alignItems: 'center',
  },
  scrollContent: {
    paddingBottom: 120,
  },
  imageContainer: {
    width: '100%',
    height: 380,
    backgroundColor: colors.lightGray,
    position: 'relative',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  selectorsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  dropdownButton: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  dropdownButtonText: {
    ...Typography.regular14,
    fontWeight: '500',
    color: colors.black,
  },
  favoriteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  infoContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  brandPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  brandText: {
    ...Typography.regular25,
    fontWeight: '800',
    color: colors.black,
    textTransform: 'uppercase',
    flex: 1,
    marginRight: 8,
  },
  priceText: {
    ...Typography.regular25,
    fontWeight: '800',
    color: colors.black,
  },
  nameText: {
    ...Typography.regular16,
    color: colors.gray,
    marginBottom: 8,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  starsRow: {
    flexDirection: 'row',
    marginRight: 8,
  },
  reviewCount: {
    ...Typography.regular12,
    color: colors.gray,
  },
  descriptionText: {
    ...Typography.regular14,
    color: colors.black,
    lineHeight: 21,
    marginBottom: 24,
  },
  divider: {
    height: 1,
    backgroundColor: colors.lightGray,
  },
  accordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
  },
  accordionTitle: {
    ...Typography.regular16,
    fontWeight: '600',
    color: colors.black,
  },
  accordionContent: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  accordionText: {
    ...Typography.regular14,
    color: colors.gray,
    lineHeight: 20,
  },
  relatedSection: {
    paddingVertical: 24,
    borderTopWidth: 8,
    borderTopColor: colors.lightGray,
  },
  relatedTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  relatedTitle: {
    ...Typography.regular18,
    fontWeight: '500',
    color: colors.black,
  },
  relatedItemsCount: {
    ...Typography.regular14,
    color: colors.gray,
  },
  relatedList: {
    paddingHorizontal: 12,
  },
  relatedCard: {
    width: 150,
    marginRight: 16,
    backgroundColor: colors.white,
    borderRadius: 8,
    overflow: 'visible',
    position: 'relative',
  },
  relatedImageContainer: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.lightGray,
    marginBottom: 8,
  },
  relatedImage: {
    width: '100%',
    height: '100%',
  },
  relatedBrand: {
    ...Typography.regular14,
    color: colors.gray,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  relatedName: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 4,
  },
  relatedPrice: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#EBEBEB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  modalTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalCloseText: {
    ...Typography.regular16,
    color: colors.gray,
  },
  modalOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F9F9F9',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalOptionText: {
    ...Typography.regular16,
    color: colors.black,
  },
  modalOptionTextSelected: {
    color: colors.red,
    fontWeight: '700',
  },

  // Size drawer specific styles matching the premium UI
  sizeDrawerContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: colors.white,
  },
  sizeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
    justifyContent: 'flex-start',
  },
  sizeGridItem: {
    width: '30%', // Three items in a row
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D2D2D2',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  sizeGridItemActive: {
    borderColor: colors.black,
    borderWidth: 1.5,
  },
  sizeGridText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  sizeGridTextActive: {
    color: colors.black,
    fontWeight: '700',
  },
  sizeInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
    marginBottom: 24,
  },
  sizeInfoText: {
    ...Typography.regular16,
    color: colors.black,
    fontWeight: '500',
  },
  sizeInfoChevron: {
    ...Typography.regular16,
    color: colors.black,
    fontWeight: '300',
  },
  addToCartButton: {
    width: '100%',
  },
});
