import { colors } from '../theme';

export const bagPageConstants = {
  addedToFavourites: 'Added to Favourites',
  favoritedMessage: 'has been favorited!',
  promoApplied: 'Promo Applied',
  promoAppliedMessage: (code: string) => `Discount code "${code}" applied!`,
  invalidPromo: 'Invalid Promo',
  invalidPromoMessage: 'The promo code entered does not exist or is expired.',
  colorLabel: 'Color:',
  sizeLabel: ' Size:',
  currencySymbol: '$',
  addToFavorites: 'Add to favorites',
  deleteFromList: 'Delete from the list',
  myBagTitle: 'My Bag',
  emptyBagMessage: 'Your shopping bag is empty. Start adding items from the Shop!',
  shopNow: 'Shop Now',
  enterPromoPlaceholder: 'Enter your promo code',
  totalAmountLabel: 'Total amount:',
  checkoutBtn: 'CHECK OUT',
  yourPromoCodesTitle: 'Your Promo Codes',
  percentOff: '% off',
  applyBtn: 'Apply',
  emptyString: '',
  bottomTabRoute: 'BottomTab',
  shopScreenRoute: 'ShopScreen',
  shopIndexRoute: 'ShopIndex',
  checkoutTitle: 'Checkout',
  shippingAddressTitle: 'Shipping address',
  changeBtn: 'Change',
  paymentTitle: 'Payment',
  deliveryMethodTitle: 'Delivery method',
  orderLabel: 'Order:',
  deliveryLabel: 'Delivery:',
  summaryLabel: 'Summary:',
  submitOrderBtn: 'SUBMIT ORDER',
  paymentMethodsTitle: 'Payment methods',
  yourPaymentCardsTitle: 'Your payment cards',
  useDefaultCheckboxLabel: 'Use as default payment method',
  addNewCardTitle: 'Add new card',
  nameOnCardLabel: 'Name on card',
  cardNumberLabel: 'Card number',
  expireDateLabel: 'Expire Date',
  cvvLabel: 'CVV',
  setDefaultCheckboxLabel: 'Set as default payment method',
  addCardBtn: 'ADD CARD',
  successTitle: 'Success!',
  successSubtext: 'Your order will be delivered soon.\nThank you for choosing our app!',
  continueShoppingBtn: 'CONTINUE SHOPPING',
  homeScreenRoute: 'HomeScreen',
  paymentMethodsScreenRoute: 'PaymentMethodsScreen',
  successScreenRoute: 'SuccessScreen',
  courierFedex: 'fedex',
  courierUsps: 'usps',
  courierDhl: 'dhl',
  courierFedexLabel: 'FedEx',
  courierUspsLabel: 'USPS',
  courierDhlLabel: 'DHL',
  deliveryTimeLabel: '2-3 days',
  brandVisa: 'Visa',
  brandMastercard: 'Mastercard',
  brandUnknown: 'Unknown',
  defaultCard1Id: 'card_1',
  defaultCard2Id: 'card_2',
  defaultCard1Holder: 'Jennyfer Doe',
  defaultCard2Holder: 'Jennyfer Doe',
  defaultCard1Expiry: '05/23',
  defaultCard2Expiry: '11/22',
  defaultCard1Last4: '3947',
  defaultCard2Last4: '4546',
  themeBlack: 'black',
  themeSilver: 'silver',
  themePurple: 'purple',
  cardHolderNameLabel: 'Card Holder Name',
  defaultShipName: 'Jane Doe',
  defaultShipAddress: '3 Newbridge Court',
  defaultShipCity: 'Chino Hills',
  defaultShipState: 'CA',
  defaultShipZip: '91709',
  defaultShipCountry: 'United States',
  cancelBtnLabel: 'Cancel',
  saveBtnLabel: 'Save',
  processingBtnLabel: 'PROCESSING...',
  securingCardBtnLabel: 'SECURING CARD...',
  plusSymbol: '+',
  fullNameInputLabel: 'Full Name',
  addressLineInputLabel: 'Address Line',
  cityInputLabel: 'City',
  stateInputLabel: 'State',
  zipCodeInputLabel: 'Zip Code',
  countryInputLabel: 'Country',
  toastTypeSuccess: 'success',
  toastTypeInfo: 'info',
  toastTypeError: 'error',
  toastAddressUpdated: 'Shipping Address Updated',
  toastAddressSaved: 'Delivery address has been saved.',
  toastTokenizingCard: 'Tokenizing Card...',
  toastSecuringStripe: 'Securing details with Stripe network...',
  toastCardAdded: 'Card Added Successfully',
  toastCreatingOrder: 'Creating Order...',
  toastPreparingPayment: 'Preparing your payment transaction...',
  toastPaymentAuthorized: 'Payment Authorized (Test Mode)',
  toastBypassedSDK: 'Bypassed client SDK check.',
  toastProcessingGateway: 'Processing Gateway...',
  toastConfirmingPayment: 'Confirming your secure payment...',
  toastPaymentCancelled: 'Payment Cancelled',
  toastCancelledDetail: 'You cancelled the transaction.',
  toastAuthFailed: 'Payment Authorization Failed',
  toastVerifyingTransaction: 'Verifying Transaction...',
  toastCheckingStatus: 'Checking transaction status on payment nodes.',
  toastOrderSuccessful: 'Order Successful!',
  toastOrderPlaced: 'Your order has been placed successfully.',
  errorValidationTitle: 'Validation Error',
  errorValidationName: 'Please enter the name on the card.',
  errorValidationCardNumber: 'Please enter a valid credit card number.',
  errorValidationExpiry: 'Please enter a valid expiry date (MM/YY).',
  errorValidationCvv: 'Please enter a valid CVV.',
  errorCardAdditionTitle: 'Card Addition Error',
  errorCardAdditionDetail: 'Could not verify card details.',
  errorClientSecret: 'Failed to obtain client secret from payment server.',
  errorVerificationRejected: 'Verification rejected by backend.',
  errorOrderProcessingTitle: 'Order Processing Error',
  errorFinalizingOrder: 'An error occurred while finalizing your order.',
  brandVisaLc: 'visa',
  brandMastercardLc: 'mastercard',
  offlineModeLabel: 'Offline mode',
  securedLabel: 'Secured',
  stripePmPrefix: 'pm_',
  stripeMockPrefix: 'card_mock',
  stripeCustomPrefix: 'card_custom',
  currencyUsd: 'usd',
  testVisaPaymentMethod: 'pm_card_visa',
  checkoutViewMode: 'checkout',
  savedCardsViewMode: 'saved_cards',
  toastConfirmingMock: 'Confirming secure mockup card...',
  confirmResultCancelCode: 'Canceled',
  countryUsCode: 'US',
  cardNumberMask: '•••• •••• •••• ',
  defaultCardNumberPlaceholder: '5546 8205 3693 3947',
  expireDatePlaceholder: 'MM/YY',
  cvvPlaceholder: '567',
} as const;

export interface StaticPromoCode {
  id: string;
  discount: number;
  label: string;
  title: string;
  code: string;
  validity: string;
  color: string;
}

export const STATIC_PROMO_CODES: StaticPromoCode[] = [
  {
    id: 'mypromocode2020',
    discount: 10,
    label: '10% off',
    title: 'Personal offer',
    code: 'mypromocode2020',
    validity: '6 days remaining',
    color: colors.red,
  },
  {
    id: 'summer2020',
    discount: 15,
    label: '15% off',
    title: 'Summer Sale',
    code: 'summer2020',
    validity: '23 days remaining',
    color: colors.green,
  },
  {
    id: 'personal22',
    discount: 22,
    label: '22% off',
    title: 'Personal offer',
    code: 'mypromocode2020',
    validity: '6 days remaining',
    color: colors.black,
  },
];
