import { StyleSheet } from 'react-native';
import { colors } from '../../theme';
import Typography, { screenWidth } from '../../theme/fonts';

export const shopStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
  },
  headerLeft: {
    padding: 4,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
  },
  headerRight: {
    padding: 4,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightGray,
    borderRadius: 24,
    paddingHorizontal: 16,
    marginLeft: 16,
    height: 40,
    borderWidth: 1,
    borderColor: colors.lightGray,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    color: colors.black,
    padding: 0,
    ...Typography.regular14,
  },
  searchCloseText: {
    fontSize: 16,
    color: colors.gray,
    paddingHorizontal: 4,
  },
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
    backgroundColor: colors.white,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    position: 'relative',
  },
  tabText: {
    ...Typography.regular16,
    color: colors.gray,
    fontWeight: '500',
  },
  activeTabText: {
    color: colors.black,
    fontWeight: '700',
  },
  activeTabIndicator: {
    position: 'absolute',
    bottom: 0,
    height: 3,
    backgroundColor: colors.red,
    width: '100%',
  },
  scrollContent: {
    paddingBottom: 110,
  },
  bannerContainer: {
    margin: 16,
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  bannerTitle: {
    ...Typography.regular25,
    fontWeight: '900',
    color: colors.white,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  bannerSubtitle: {
    ...Typography.regular14,
    color: colors.white,
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  categoryList: {
    paddingHorizontal: 16,
  },
  categoryCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 100,
    marginBottom: 16,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    overflow: 'hidden',
    marginHorizontal: 16,
  },
  categoryTextContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 24,
  },
  categoryTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
  },
  categoryImage: {
    width: 140,
    height: '100%',
  },
  loaderContainer: {
    paddingVertical: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    paddingVertical: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    ...Typography.regular16,
    color: colors.gray,
  },

  productsHeaderContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: colors.white,
  },
  productsTitle: {
    ...Typography.regular32,
    fontWeight: '900',
    color: colors.black,
    marginBottom: 16,
  },
  tagsScrollView: {
    marginBottom: 12,
  },
  tagButton: {
    backgroundColor: colors.black,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  tagText: {
    ...Typography.regular14,
    color: colors.white,
    fontWeight: '500',
  },
  filterSortBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.lightGray,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 12,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterIconText: {
    ...Typography.regular14,
    color: colors.black,
    marginLeft: 6,
    fontWeight: '500',
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortText: {
    ...Typography.regular14,
    color: colors.black,
    marginRight: 6,
    fontWeight: '500',
  },
  viewToggleButton: {
    padding: 2,
  },
  productsListContent: {
    paddingBottom: 110,
  },

  listProductCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 120,
    marginHorizontal: 16,
    marginBottom: 16,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    position: 'relative',
  },
  listProductImage: {
    width: 110,
    height: '100%',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  listProductInfo: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  listProductBrand: {
    ...Typography.regular12,
    color: colors.gray,
    textTransform: 'uppercase',
  },
  listProductName: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starsRow: {
    flexDirection: 'row',
    marginRight: 4,
  },
  ratingCount: {
    ...Typography.regular10,
    color: colors.gray,
  },
  listProductPrice: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
  },
  favoriteButton: {
    position: 'absolute',
    bottom: -6,
    right: -6,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    zIndex: 100,
  },

  gridProductCard: {
    backgroundColor: colors.white,
    borderRadius: 8,
    width: (screenWidth - 48) / 2,
    marginHorizontal: 8,
    marginBottom: 16,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    overflow: 'visible',
    position: 'relative',
  },
  gridProductImageContainer: {
    width: '100%',
    height: 180,
    backgroundColor: colors.lightGray,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    overflow: 'hidden',
  },
  gridProductImage: {
    width: '100%',
    height: '100%',
  },
  gridProductInfo: {
    padding: 8,
  },
  gridProductBrand: {
    ...Typography.regular10,
    color: colors.gray,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  gridProductName: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 4,
  },
  gridProductPrice: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
    marginTop: 4,
  },
  gridFavoriteButton: {
    position: 'absolute',
    top: 162,
    right: -6,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
});

export const filterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
  },
  headerPlaceholder: {
    width: 32,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  sectionHeader: {
    backgroundColor: colors.lightGray,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
  },
  priceContainer: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    backgroundColor: colors.white,
  },
  priceTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  priceText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  sliderTrackContainer: {
    height: 30,
    justifyContent: 'center',
    position: 'relative',
  },
  sliderBaseTrack: {
    height: 3,
    backgroundColor: colors.gray,
    borderRadius: 2,
  },
  sliderHighlightTrack: {
    position: 'absolute',
    height: 3,
    backgroundColor: colors.red,
    borderRadius: 2,
  },
  sliderThumb: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.red,
    top: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  colorsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: colors.white,
    gap: 16,
  },
  colorOutlineContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  colorOutlineSelected: {
    borderColor: colors.red,
  },
  colorCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  colorCircleBorder: {
    borderWidth: 1,
    borderColor: colors.gray,
  },
  sizesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: colors.white,
    gap: 12,
  },
  sizeButton: {
    width: 44,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  sizeButtonSelected: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  sizeText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  sizeTextSelected: {
    color: colors.white,
  },
  categoryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: colors.white,
    gap: 10,
  },
  categoryButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  categoryButtonSelected: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  categoryText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  categoryTextSelected: {
    color: colors.white,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 18,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.lightGray,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
    marginTop: 16,
  },
  brandLeft: {
    flex: 1,
    marginRight: 16,
  },
  brandLabel: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 4,
  },
  brandValues: {
    ...Typography.regular14,
    color: colors.gray,
  },
  bottomBarContainer: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.lightGray,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },
  bottomBar: {
    backgroundColor: colors.white,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 16,
  },
  discardButton: {
    flex: 1,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  discardButtonText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
  },
  applyButton: {
    flex: 1,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.red,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  applyButtonText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.white,
  },
});

export const brandStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
  },
  headerPlaceholder: {
    width: 32,
  },
  searchSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightGray,
    borderRadius: 24,
    paddingHorizontal: 14,
    height: 40,
    borderWidth: 1,
    borderColor: colors.black,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    color: colors.black,
    paddingHorizontal: 8,
    paddingVertical: 0,
    ...Typography.regular14,
  },
  searchCloseText: {
    fontSize: 16,
    color: colors.gray,
    paddingHorizontal: 4,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  brandText: {
    ...Typography.regular16,
    fontWeight: '500',
    color: colors.black,
  },
  brandTextSelected: {
    color: colors.red,
    fontWeight: '700',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.gray,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    borderColor: colors.red,
    backgroundColor: colors.red,
  },
  emptyContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyText: {
    ...Typography.regular14,
    color: colors.gray,
  },
  bottomBarContainer: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.lightGray,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },
  bottomBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 16,
  },
  discardButton: {
    flex: 1,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  discardButtonText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
  },
  applyButton: {
    flex: 1,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.red,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  applyButtonText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.white,
  },
});
