import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../theme';
import Typography from '../../theme/fonts';

const { width } = Dimensions.get('window');

export const bagScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightGray,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: colors.white,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
  },
  searchButton: {
    padding: 8,
  },
  scrollContent: {
    paddingBottom: 220,
  },
  cartList: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 180,
  },
  cartCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 140,
    marginBottom: 16,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    position: 'relative',
    overflow: 'visible',
  },
  imageContainer: {
    width: 100,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    overflow: 'hidden',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  infoContainer: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  brandText: {
    ...Typography.regular18,
    color: colors.gray,
    textTransform: 'uppercase',
  },
  nameText: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metaText: {
    ...Typography.regular14,
    color: colors.gray,
  },
  metaValue: {
    ...Typography.regular14,
    color: colors.black,
    fontWeight: '600',
  },
  quantityPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  quantityButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  quantityButtonText: {
    ...Typography.regular14,
    fontWeight: 'bold',
    color: colors.gray,
  },
  quantityText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  priceText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
  },
  menuPopover: {
    position: 'absolute',
    top: 36,
    right: 12,
    backgroundColor: colors.white,
    borderRadius: 8,
    paddingVertical: 4,
    width: 170,
    elevation: 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    zIndex: 1000,
  },
  menuItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  menuItemText: {
    ...Typography.regular13,
    color: colors.black,
    fontWeight: '500',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#F3F3F3',
  },
  promoContainer: {
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderTopRightRadius: 50,
    borderBottomRightRadius : 50,
    borderTopLeftRadius : 10,
    borderBottomLeftRadius : 10,
    elevation: 2,
    shadowColor: colors.gray,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    height: 48,
  },
  promoInput: {
    flex: 1,
    paddingHorizontal: 16,
    ...Typography.regular14,
    color: colors.black,
  },
  promoButton: {
    height: 48,
    width: 48,
    borderRadius: 50,
    backgroundColor: colors.black,
    color: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    // marginRight: 6,
  },
  appliedPromoWrapper: {
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 8,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    height: 48,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
  },
  appliedPromoText: {
    ...Typography.regular14,
    color: colors.black,
    fontWeight: '500',
  },
  appliedPromoCancel: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F3F3F3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  appliedPromoCancelText: {
    ...Typography.regular12,
    fontWeight: 'bold',
    color: colors.gray,
  },
  promoSheetContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 40,
    backgroundColor: colors.lightGray,
  },
  promoSheetInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 48,
    marginBottom: 24,
    elevation: 1,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 1,
  },
  promoSheetInput: {
    flex: 1,
    paddingHorizontal: 16,
    ...Typography.regular14,
    color: colors.black,
  },
  promoSheetTitle: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 16,
  },
  promoList: {
    gap: 16,
  },
  promoCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 80,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    overflow: 'hidden',
  },
  promoCardLeft: {
    width: 80,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  promoCardLeftImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  promoCardLeftText: {
    ...Typography.regular25,
    fontWeight: '800',
    color: colors.white,
  },
  promoCardLeftSubtext: {
    ...Typography.regular10,
    fontWeight: '700',
    color: colors.white,
    marginTop: -4,
  },
  promoCardMiddle: {
    flex: 1,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  promoCardTitle: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 2,
  },
  promoCardCode: {
    ...Typography.regular12,
    color: colors.black,
    fontWeight: '500',
  },
  promoCardValidity: {
    ...Typography.regular12,
    color: colors.gray,
    marginTop: 6,
  },
  promoCardRight: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: 12,
  },
  promoApplyButton: {
    backgroundColor: colors.red,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
  },
  promoApplyButtonText: {
    ...Typography.regular12,
    color: colors.white,
    fontWeight: '700',
  },
  summaryContainer: {
    position: 'absolute',
    bottom: 96,
    left: 16,
    right: 16,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    elevation: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  summaryLabel: {
    ...Typography.regular14,
    color: colors.gray,
    fontWeight: '500',
  },
  summaryValue: {
    ...Typography.regular18,
    color: colors.black,
    fontWeight: '700',
  },
  checkoutButton: {
    backgroundColor: colors.red,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 100,
  },
  emptyText: {
    ...Typography.regular16,
    color: colors.gray,
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 24,
  },
});
