import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../theme';
import Typography from '../../theme/fonts';

const { width } = Dimensions.get('window');
const cardWidth = (width - 48) / 2; 

export const favScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightGray,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: colors.white,
  },
  headerTitle: {
    ...Typography.regular18,
    fontWeight: '700',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
    marginLeft: 32,
  },
  searchButton: {
    padding: 8,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  categoryScroll: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
  },
  categoryPill: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryPillActive: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  categoryText: {
    ...Typography.regular14,
    color: colors.black,
    fontWeight: '600',
  },
  categoryTextActive: {
    color: colors.white,
  },
  filterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.lightGray,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterText: {
    ...Typography.regular13,
    color: colors.black,
    fontWeight: '500',
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sortText: {
    ...Typography.regular13,
    color: colors.black,
    fontWeight: '500',
  },
  viewButton: {
    padding: 4,
  },
  productList: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 120,
  },
  gridRow: {
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  gridProductCard: {
    backgroundColor: colors.white,
    borderRadius: 8,
    width: cardWidth,
    marginBottom: 16,
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    overflow: 'visible',
    position: 'relative',
  },
  gridProductImageContainer: {
    width: '100%',
    height: 180,
    backgroundColor: colors.lightGray,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    position: 'relative',
  },
  gridProductImage: {
    width: '100%',
    height: '100%',
  },
  gridProductInfo: {
    padding: 8,
    paddingTop: 12,
  },
  gridProductBrand: {
    ...Typography.regular10,
    color: colors.gray,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  gridProductName: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 4,
  },
  gridProductPrice: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
    marginTop: 4,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starsRow: {
    flexDirection: 'row',
    marginRight: 4,
  },
  ratingCount: {
    ...Typography.regular10,
    color: colors.gray,
  },
  gridDiscountBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colors.dangerRed,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    zIndex: 2,
  },
  gridDiscountText: {
    fontSize: 10,
    color: colors.white,
    fontWeight: '700',
  },
  gridDeleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  gridSoldOutOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.lightGray,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  gridSoldOutText: {
    fontSize: 10,
    color: colors.black,
    fontWeight: '600',
    textAlign: 'center',
  },
  gridFloatingBagButton: {
    position: 'absolute',
    bottom: -18,
    right: -6,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.dangerRed,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  listProductCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 8,
    height: 120,
    marginBottom: 16,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    position: 'relative',
    overflow: 'visible',
  },
  listProductImageContainer: {
    width: 110,
    height: '100%',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  listProductImage: {
    width: '100%',
    height: '100%',
  },
  listProductInfo: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  listProductBrand: {
    ...Typography.regular12,
    color: colors.gray,
    textTransform: 'uppercase',
  },
  listProductName: {
    ...Typography.regular16,
    fontWeight: '700',
    color: colors.black,
  },
  listProductPrice: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.black,
  },
  listDiscountBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colors.dangerRed,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    zIndex: 2,
  },
  listDiscountText: {
    fontSize: 10,
    color: colors.white,
    fontWeight: '700',
  },
  listDeleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  listSoldOutOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.lightGray,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  listSoldOutText: {
    fontSize: 10,
    color: colors.black,
    fontWeight: '600',
    textAlign: 'center',
  },
  listFloatingBagButton: {
    position: 'absolute',
    bottom: -6,
    right: -6,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.dangerRed,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  metaText: {
    ...Typography.regular14,
    color: colors.gray,
    marginTop: 2,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  originalPriceText: {
    ...Typography.regular12,
    color: colors.gray,
    textDecorationLine: 'line-through',
  },
  discountPriceText: {
    ...Typography.regular14,
    fontWeight: '700',
    color: colors.dangerRed,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 120,
    paddingHorizontal: 24,
  },
  emptyText: {
    ...Typography.regular16,
    color: colors.gray,
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 24,
  },
  sizeDrawerContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: colors.white,
  },
  sizeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
    justifyContent: 'flex-start',
  },
  sizeGridItem: {
    width: '30%',
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  sizeGridItemActive: {
    borderColor: colors.black,
    borderWidth: 1.5,
  },
  sizeGridText: {
    ...Typography.regular14,
    fontWeight: '600',
    color: colors.black,
  },
  sizeGridTextActive: {
    color: colors.black,
    fontWeight: '700',
  },
});
